

import javax.swing.table.DefaultTableModel;
import conections.ConnectionSQL;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import models.Cliente;
import repositorio.ClienteRepository;

public class frmClientes extends javax.swing.JFrame {
ConnectionSQL adaptador=new ConnectionSQL();

Connection conexion=adaptador.Conexion();
DefaultTableModel modelo;
Statement st;
ResultSet rs;
ClienteRepository repositorio;
    public frmClientes() {
        initComponents();
            modelo=(DefaultTableModel)Tabla.getModel();
         SetImageLabel(jLabel20,"src/imagen/clientesinfondo.png");
        this.getContentPane().setBackground(Color.pink);
        setLocationRelativeTo(null);
        repositorio=new ClienteRepository(conexion);
       consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblclientes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        lblsexo = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtnit = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));

        lblclientes.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblclientes.setText("Clientes.");

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel1.setText("NIT.");

        lblnombre.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblnombre.setText("Nombres:");

        lblapellidos.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblapellidos.setText("Apellidos:");

        lbledad.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lbledad.setText("Edad:");

        lblsexo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblsexo.setText("Sexo:");

        lbldireccion.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lbldireccion.setText("Direccion:");

        txtnombre.setBackground(new java.awt.Color(204, 204, 204));
        txtnombre.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 102));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
        });

        txtapellido.setBackground(new java.awt.Color(204, 204, 204));
        txtapellido.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(0, 0, 102));
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidoKeyPressed(evt);
            }
        });

        txtedad.setBackground(new java.awt.Color(204, 204, 204));
        txtedad.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtedad.setForeground(new java.awt.Color(0, 0, 102));
        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtedadKeyPressed(evt);
            }
        });

        txtdireccion.setBackground(new java.awt.Color(204, 204, 204));
        txtdireccion.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 102));
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
        });

        txtnit.setBackground(new java.awt.Color(204, 204, 204));
        txtnit.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtnit.setForeground(new java.awt.Color(0, 0, 102));
        txtnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnitKeyPressed(evt);
            }
        });

        jComboBoxSexo.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxSexo.setForeground(new java.awt.Color(0, 0, 102));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jComboBoxSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxSexoKeyPressed(evt);
            }
        });

        Tabla.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nit", "Nombre", "Apellido", "Edad", "sexo", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla.setGridColor(new java.awt.Color(153, 153, 0));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        btnguardar.setBackground(new java.awt.Color(153, 204, 255));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(153, 204, 255));
        btnmodificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(153, 204, 255));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(153, 204, 255));
        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtnit)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(630, 630, 630))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(341, 341, 341)
                                .addComponent(lblclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblapellidos)
                                    .addComponent(lblnombre)
                                    .addComponent(lbledad)
                                    .addComponent(lblsexo)
                                    .addComponent(lbldireccion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblclientes)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnombre)
                        .addGap(11, 11, 11)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblapellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbledad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsexo)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbldireccion)
                        .addGap(18, 18, 18)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(btnnuevo)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       agregar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       eliminar();
       consulta();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
      modificar();
      limpiartabla();
      consulta();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        try{
            int fila=Tabla.getSelectedRow();
            int id= Integer.parseInt((Tabla.getValueAt(fila,0).toString()));
            PreparedStatement ps;
            ResultSet rs;
            conexion=adaptador.Conexion();
            ps=adaptador.Conexion().prepareStatement("select nit,nombre,apellidos,edad,sexo,direccion from cliente where id=?");
            ps.setInt(1, id);
            rs=ps.executeQuery();
            while(rs.next()){
                txtid.setText(String.valueOf(id));
                txtnit.setText(rs.getString("nit"));
                txtnombre.setText(rs.getString("nombre"));
                txtapellido.setText(rs.getString("apellidos"));
                txtedad.setText(rs.getString("edad"));
                jComboBoxSexo.getSelectedItem().toString();
                txtdireccion.setText(rs.getString("direccion"));
                
            }
            
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
    
        txtnit.setText("");
       txtnombre.setText("");
       txtapellido.setText("");
       txtedad.setText("");
       txtdireccion.setText("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnitKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtnombre.requestFocus();
       
    }   
    }//GEN-LAST:event_txtnitKeyPressed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtapellido.requestFocus();
       
    }   
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtapellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          txtedad.requestFocus();
       
    }           
    }//GEN-LAST:event_txtapellidoKeyPressed

    private void txtedadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          jComboBoxSexo.requestFocus();
       
    }   
    }//GEN-LAST:event_txtedadKeyPressed

    private void jComboBoxSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxSexoKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           txtdireccion.requestFocus();
       
    }   
    }//GEN-LAST:event_jComboBoxSexoKeyPressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           btnguardar.requestFocus();
       
    }   
    }//GEN-LAST:event_txtdireccionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }
void consulta(){
      try{
           ArrayList<Cliente> clientes=repositorio.read();
           
           for(Cliente cliente:clientes){
               Object[] fila= new Object[7];
               fila[0]=cliente.getId();
               fila[1]=cliente.getNit();
               fila[2]=cliente.getNombre();
               fila[3]=cliente.getApellidos();
               fila[4]=cliente.getEdad();
               fila[5]=cliente.getSexo();
               fila[6]=cliente.getDireccion();
               modelo=(DefaultTableModel)Tabla.getModel();
               modelo.addRow(fila);
           }
       }catch(Exception e){
           System.out.println(e);
       }
}
void agregar(){
   try{
          Cliente clienteCREADO=repositorio.create(txtnit.getText(), txtnombre.getText(), txtapellido.getText(),txtedad.getText(),jComboBoxSexo.getSelectedItem().toString(),txtdireccion.getText());
          
          Object[] fila=new Object[7];
          fila[0]=clienteCREADO.getId();
          fila[1]=clienteCREADO.getNit();
          fila[2]=clienteCREADO.getNombre();
          fila[3]=clienteCREADO.getApellidos();
          fila[4]=clienteCREADO.getEdad();
          fila[5]=clienteCREADO.getSexo();
          fila[6]=clienteCREADO.getDireccion();
         
          modelo.addRow(fila);
          JOptionPane.showMessageDialog(this, "Cliente Guardado");
      }catch(Exception e ){
          JOptionPane.showMessageDialog(this, "Error al guardar cliente");
          System.out.println(e);
      }
}
void modificar(){
    int id;
       try{
          Cliente clienteModificado=repositorio.update(id=Integer.parseInt(txtid.getText()), new Cliente (0,txtnit.getText(),txtnombre.getText(),txtapellido.getText(),txtedad.getText(),jComboBoxSexo.getSelectedItem().toString(),txtdireccion.getText()));
           Object[] fila=new Object[7];
           fila[0]=clienteModificado.getId();
           fila[1]=clienteModificado.getNit();
           fila[2]=clienteModificado.getNombre();
            fila[3]=clienteModificado.getApellidos();
           fila[4]=clienteModificado.getEdad();
           fila[5]=clienteModificado.getSexo();
           fila[6]=clienteModificado.getDireccion();
                  modelo.addRow(fila);
                  limpiartabla();
                  JOptionPane.showMessageDialog(this, "Cliente Modificado");
          
       }catch(Exception e ){
       JOptionPane.showMessageDialog(this, "Error al guardar Cliente");
           System.out.println(e);
       }
}
void limpiartabla(){
    for(int i=0;i<Tabla.getRowCount();i++){
        modelo.removeRow(i);
        i=i-1;
    }
}
void eliminar(){
    int id=Integer.parseInt(txtid.getText());
    try{
        repositorio.delete(id);
        JOptionPane.showMessageDialog(this, "Registro eliminado");
        limpiartabla();
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
        System.out.println(e);
    }
}
private void SetImageLabel(JLabel labelName,String root){
    ImageIcon image=new ImageIcon(root);
    Icon icon=new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(),labelName.getHeight(),Image.SCALE_DEFAULT));
    labelName.setIcon(icon);
    this.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblclientes;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnit;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
